### ISSUE TITLE
Number of Width Segments

### ISSUE THREAD

**Issue by mcsherrill** [wingtorres/morphometrix#11]
Using the new code with the "Matrix representation of Bezier curves" (__main__.py), the "# Width Segments" now corresponds to the actual number of width lines drawn rather than the number of segments the animal is divided into. Setting the # of Width Segments to 20 now divides the animal into 21 segments. 
<img width="1148" alt="Screen Shot 2022-06-06 at 6 55 33 PM" src="https://user-images.githubusercontent.com/107007397/172263792-2aeeb9a8-a38a-4521-a4af-5e3941719565.png">

**Comment by cbirdferrer** [comment]
hi! Just wanted to follow up and say that I think it has to do with needing to subtract 1 from self.numwidths

it's present in L723 ```self.widths[-1] = np.empty(self.numwidths - 1, dtype='float') ```

which explains why there are 19 headers in the output.

but it's missing/commented out in L728 ```self.nspines = 2 * (self.numwidths) #- 1)```

**Comment by perkinstaylorc** [comment]
Hey @cbirdferrer, I am having the same issue and was wondering if you ever managed to resolve it. I tried removing the # in L728 like you suggested, but that did not resolve the problem. I also noticed that for the Morphometrix output csv file, there is always one less width measurement than the number of segments entered. 

As an example, if I enter in that I want 10 width segments (and it currently incorrectly gives me 10 width lines, so the animal is divided into 11 segments), then the output csv only has 9 measurements. This seems incorrect though because there should be one measurement corresponding to each width segment (i.e. an animal divided into 10 equal parts with 9 width segment lines should have 9 width segments).

Any advice or help that you may have for resolving this issue would be greatly appreciated!
